# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatuser',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='created',
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='updated',
        ),
        migrations.AddField(
            model_name='chat',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
