# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20170519_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgroup',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.Groupp'),
            preserve_default=False,
        ),
    ]
