# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_postgroup_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupp',
            old_name='admin',
            new_name='author',
        ),
    ]
