# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20170519_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupuser',
            old_name='user',
            new_name='author',
        ),
    ]
