# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0006_auto_20170519_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('like_count', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='postgroup',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgroup',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postgroup',
            name='short_content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postgroup',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postgroup',
            name='content',
            field=models.TextField(verbose_name='post_content'),
        ),
        migrations.AlterField(
            model_name='postgroup',
            name='title',
            field=models.CharField(max_length=255, verbose_name='post_title'),
        ),
        migrations.AddField(
            model_name='commentgroup',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.PostGroup'),
        ),
    ]
