# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(1, 'post'), (2, 'comment'), (3, 'like')], default=1, max_length=2),
        ),
    ]
