# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to=settings.AUTH_USER_MODEL)),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('iniciator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciator', to=settings.AUTH_USER_MODEL)),
                ('repliciant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repliciant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
