# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_auto_20170214_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='post_content'),
        ),
    ]
