# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_post_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
